const h1 = 70
const h2 = 45
const h3 = 17

const config = {
    animationTime: 5000,
    transitionTime: 1000,
    scene1: {
        h: h1,
        duration: 5000,
    },
    scene2: {
        h: h2,
        duration: 6000,
        newPosition: [7.5, 10 + h2, 0],
        newVelocity: [0, 0, 0],
    },
    scene3: {
        h: h3,
        duration: 9000,
        newPosition: [-14, 15 + h3, 0],
        newVelocity: [-0.85, -2.36, 0],
    },
    width: window.innerWidth,
    height: window.innerHeight,
    collisionDict: {
        'Dynamic': 0,
        'Static': 1,
        'Kinematic': 2,
        'Ghost': 4
    },
    spheres: [
        {
            name: 'mainBall',
            castShadow: true,
            position: [0, 15 + h1, 0],
            rotation: [0, 0, 0],
            scale: [1, 1, 1],
            color: 0xff475a,
            collisionType: 'Dynamic',
        }
    ],
    boxes: [
        {
            name: 'plane straight',
            castShadow: true,
            position: [-3.3, 6.45 + h1, 0],
            rotation: [Math.PI / 2, 0, 0],
            scale: [4, 3, .5],
            color: 0x9cf8fc,
            collisionType: 'Kinematic',
        },
        {
            name: 'plane tilted',
            castShadow: true,
            position: [0, 6 + h1, 0],
            rotation: [Math.PI / 2, -Math.PI / 10, 0],
            scale: [3, 3, .5],
            color: 0x9cf8fc,
            collisionType: 'Kinematic',
        },
        {
            name: 'plane tilted2',
            castShadow: true,
            position: [2, 5 + h2, 0],
            rotation: [Math.PI / 2, Math.PI / 10, 0],
            scale: [18, 3, .5],
            color: 0x9cf8fc,
            collisionType: 'Kinematic',
        },
        {
            name: 'vertical wall',
            castShadow: true,
            position: [-17, 7.25 + h3, 0],
            rotation: [Math.PI / 2, -Math.PI / 2, 0],
            scale: [5, 3, .5],
            color: 0x9cf8fc,
            collisionType: 'Kinematic',
        },
        {
            name: 'stairs1',
            castShadow: true,
            position: [-15, 5 + h3, 0],
            rotation: [Math.PI / 2, 0, 0],
            scale: [4, 3, .5],
            color: 0x9cf8fc,
            collisionType: 'Kinematic',
        },
        {
            name: 'stairs2',
            castShadow: true,
            position: [-10, 3 + h3, 0],
            rotation: [Math.PI / 2, 0, 0],
            scale: [4, 3, .5],
            color: 0x9cf8fc,
            collisionType: 'Kinematic',
        },
        {
            name: 'stairs3',
            castShadow: true,
            position: [-5, 1 + h3, 0],
            rotation: [Math.PI / 2, 0, 0],
            scale: [4, 3, .5],
            color: 0x9cf8fc,
            collisionType: 'Kinematic',
        },
        {
            name: 'plane plain front',
            castShadow: true,
            position: [0, -5 + h3, 10],
            rotation: [Math.PI / 2.4, 0, 0],
            scale: [15, 3, .5],
            color: 0x9cf8fc,
            collisionType: 'Kinematic',
        },
        {
            name: 'wall',
            castShadow: false,
            position: [0, 40, -2],
            rotation: [0, 0, 0],
            scale: [60, 120, 2],
            color: 0x38F0FA,
            collisionType: 'Kinematic',
        }
    ],
    cylinders: [
        {
            name: 'cylinder0',
            castShadow: true,
            position: [3, 3 + h1, 0],
            rotation: [Math.PI / 2, -Math.PI / 10, 0],
            color: 0x9cf8fc,
            collisionType: 'Kinematic',
            radiusTop: .3,
            radiusBottom: .3,
            height: 1.5,
        },
        {
            name: 'cylinder1',
            castShadow: true,
            position: [6, 3 + h1, 0],
            rotation: [Math.PI / 2, -Math.PI / 10, 0],
            color: 0x9cf8fc,
            collisionType: 'Kinematic',
            radiusTop: .3,
            radiusBottom: .3,
            height: 1.5,
        },
        {
            name: 'cylinder2',
            castShadow: true,
            position: [9, 3 + h1, 0],
            rotation: [Math.PI / 2, -Math.PI / 10, 0],
            color: 0x9cf8fc,
            collisionType: 'Kinematic',
            radiusTop: .3,
            radiusBottom: .3,
            height: 1.5,
        },
        {
            name: 'cylinder3',
            castShadow: true,
            position: [5, 0 + h1, 0],
            rotation: [Math.PI / 2, -Math.PI / 10, 0],
            color: 0x9cf8fc,
            collisionType: 'Kinematic',
            radiusTop: .3,
            radiusBottom: .3,
            height: 1.5,
        },
        {
            name: 'cylinder4',
            castShadow: true,
            position: [8, 0 + h1, 0],
            rotation: [Math.PI / 2, -Math.PI / 10, 0],
            color: 0x9cf8fc,
            collisionType: 'Kinematic',
            radiusTop: .3,
            radiusBottom: .3,
            height: 1.5,
        },
        {
            name: 'cylinder5',
            castShadow: true,
            position: [11, 0 + h1, 0],
            rotation: [Math.PI / 2, -Math.PI / 10, 0],
            color: 0x9cf8fc,
            collisionType: 'Kinematic',
            radiusTop: .3,
            radiusBottom: .3,
            height: 1.5,
        },
        {
            name: 'cylinder6',
            castShadow: true,
            position: [4, -3 + h1, 0],
            rotation: [Math.PI / 2, -Math.PI / 10, 0],
            color: 0x9cf8fc,
            collisionType: 'Kinematic',
            radiusTop: .3,
            radiusBottom: .3,
            height: 1.5,
        },
        {
            name: 'cylinder7',
            castShadow: true,
            position: [7, -3 + h1, 0],
            rotation: [Math.PI / 2, -Math.PI / 10, 0],
            color: 0x9cf8fc,
            collisionType: 'Kinematic',
            radiusTop: .3,
            radiusBottom: .3,
            height: 1.5,
        },
        {
            name: 'cylinder8',
            castShadow: true,
            position: [10, -3 + h1, 0],
            rotation: [Math.PI / 2, -Math.PI / 10, 0],
            color: 0x9cf8fc,
            collisionType: 'Kinematic',
            radiusTop: .3,
            radiusBottom: .3,
            height: 1.5,
        },
    ],
    gltfObjects: [
        {
            name: 'moon1',
            castShadow: true,
            url: './assets/Moon.glb',
            position: [-12, -3 + h2, 0],
            rotation: [Math.PI / 2, Math.PI / 3.1, 0],
            scale: [3, 3, 3],
            color: 0x9cf8fc,
            collisionType: 'Kinematic',
        },
        {
            name: 'moon2',
            castShadow: true,
            url: './assets/Moon.glb',
            position: [-8, -3.95 + h2, 0],
            rotation: [Math.PI / 2, -Math.PI / 1.1, 0],
            scale: [3, 3, 3],
            color: 0x9cf8fc,
            collisionType: 'Kinematic',
        },
        {
            name: 'moon3',
            castShadow: true,
            url: './assets/Moon.glb',
            position: [0, h3 - 1.15, 0],
            rotation: [ -Math.PI / 2.2, -Math.PI / 2, 0],
            scale: [2, 30, 2],
            color: 0x9cf8fc,
            collisionType: 'Kinematic',
        },
    ],
    spotlights: [
        {
            position: [150, 200, 400],
            targetPosition:[0, 45, 0],
            castShadow: true,
            shadowNear: 1,
            shadowFar: 1000,
            shadowFov: 100,
            shadowWidth: 1024 * 2,
            shadowHeight: 1024 * 2,
            angle: Math.PI / 12,
            penumbra: 0.349,
            decay: 2,
            distance: 2000,
        },
    ]
}

export { config }